### ISSUE TITLE
Using with Box64 on Asahi Linux

### ISSUE THREAD

**Issue by AwesomeCoder412412** [OpenSteamClient/OpenSteamClient#41]
While this is a 64 bit application, the readme mentions it uses a 32-bit steamservice for some functionality. I have a 64-bit OpenGL Linux game on Steam I want to run on Asahi Linux using box64. Since Asahi doesn't support 32-bit code, is it possible to run this client to the point where it could at least download and run games without using box86 at all?

**Comment by Rosentti** [comment]
Downloading and running games should be possible. It's not entirely clear what all functionality needs steamservice, however I know it includes the following:
- VAC
- Proton (maybe compat layers in general), still seems to be playable without
- Install and uninstall scripts

**Comment by AwesomeCoder412412** [comment]
Ah, shucks. The game I'm trying to run in question is Team Fortress 2 (which is getting a 64 bit update), so no VAC most likely spells the end for that endeavor. There are some other games I might try, though. Thanks for the quick response!

**Comment by Rosentti** [comment]
I'm still hopeful Valve will someday release a 64-bit client with all the parts of it being 64-bit, so 32-bit stuff would no longer be needed. I've also thought about making our own steamservice with our experimental IPCClient, but VAC probably wouldn't work, since all the binaries are signed with a .valvesig section.

Oh and you should be able to play on servers without VAC just fine, if you just want to test out TF2.
